# -*- coding: utf-8 -*-
"""meeting minutes genarator.ipynd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_OpaKf5DADfWYQP6bLqBGV3Ny9D1SRm
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

meeting_title = input("Enter meeting title: ")
data = input("Enter meeting date(DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participation (comma separated): ")
agenda = input("Enter agenda points (comma separated): ")
decisions = input("Enter decisions taken (comma separated): ")
action_items = input("Enter action  items (comma separated): ")
prepared_by = input("prepared by: ")

participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
action_items_list = [a.strip() for a in action_items.split(",") if a.strip()]

minutes = {
    "Meeting Title": meeting_title,
    "Data" : data,
    "Time" : time,
    "Participants" : ", ".join(participants_list),
    "Agenda" : ", ".join(agenda_list),
    "Desicions Taken" : "; ".join(decisions_list),
    "Action Items" : "; ".join(actions_list),
    "Prepared By" : prepared_by,
    "Genarated on": datatime.now().strftime("%d-%m-%Y %H:%M:%S")
}

df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting minutes Generated Successfully\n")
display(df)

df.to_csv("meeting_mminutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")