# -*- coding: utf-8 -*-
"""text gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B86ZqRLIPsmhT36a4UpNge_XIejM4efl
"""

from transformers import pipeline
generator = pipeline("text-generation", model="gpt2")
prompt = "artifical intelligence in hosptial mangement"
result = generator(prompt, max_length=50, num_return_sequences=1)
print("AI generated text:")
print(result[0]['generated_text'])