# -*- coding: utf-8 -*-
"""TIMETABLE GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JBDQ1y_F8OxNdHU24j7B_Z9zXpaFe--w
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

meeting_title = input("Enter meeting title: ")
data = input("Enter meeting data(DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participation (comma separated): ")



import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

subjects_input = input("Enter subjects (comma separated):")
days_input = input("Enter days(comma separated):")
periods_per_day = int(input("Enter number of periods per day:"))

subjects = [s.strip() for s in subjects_input.split(",")if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

if len(subjects) == 0 or len(days) == 0 or periods_per_day <= 0:
   print("Invalid input. please try again.")
else:
     timetable = {}

     for day in days:
         timetable[day] = random.choices(subjects, k=periods_per_day)
     df = pd.DataFrame(timetable)
     df.index = [f"period{i+1}" for i in range(periods_per_day)]

     print("\nTimetable Generate Successfully\n")
     display(df)

     df.to_csv("timetable.csv")
     print("\nTimetable saved a timetable.csv")